repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

helmDefaults:
  verify: true
  wait: true
  recreatePods: true

releases:
  - name: api
    chart: ./charts/api
    values:
      - image:
          tag: local
          pullPolicy: Always

  - name: redis
    chart: stable/redis
    version: 9.2.1
    recreatePods: false
    values:
      - cluster:
          enabled: false
