apiVersion: v1
kind: Service
metadata:
  name: {{ include "bsqt-api.fullname" . }}
  labels:
{{ include "bsqt-api.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bsqt-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
