# Default values for api.

replicaCount: 1

image:
  repository: docker.bsqt.io/bsqt/api
  tag:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}
